### ISSUE TITLE
What is the typeface used in the preview images?

### ISSUE THREAD

**Issue by giantspeck** [mgmeyers/vscode-markdown-theme#1]
I really like that monospaced typeface with the single-storey "a".  Do you happen to know the name of the font?

**Comment by mgmeyers** [comment]
Hi @giantspeck! This typeface is `Input Mono Narrow` from https://input.fontbureau.com/

Here's a link to the specific font settings I've used: https://input.fontbureau.com/preview/?size=14&language=python&theme=solarized-dark&family=InputMono&width=300&weight=300&line-height=1.2&a=ss&g=ss&i=0&l=0&zero=0&asterisk=height&braces=straight&preset=default&customize=please

**Comment by mgmeyers** [comment]
Added a link to the readme for future reference
